export const ADVANCED_SKILLS_LIST = [
  { key: "dressage",        label: "Dressage",                    cara: "Soc" },
  { key: "baratin",         label: "Baratin",                     cara: "Soc" },
  { key: "focalisation",    label: "Focalisation",                cara: "FM"  },
  { key: "empriseAnimaux",  label: "Emprise sur les animaux",     cara: "Soc" },
  { key: "esquive",         label: "Esquive",                     cara: "Ag"  },
  { key: "pistage",         label: "Pistage",                     cara: "Int" },
  { key: "soins",           label: "Soins",                       cara: "Int" },
  { key: "hypnotisme",      label: "Hypnotisme",                  cara: "FM"  },
  { key: "lectureLevres",   label: "Lecture sur les lèvres",      cara: "Int" },
  { key: "sensMagie",       label: "Sens de la magie",            cara: "FM"  },
  { key: "orientation",     label: "Orientation",                 cara: "Int" },
  { key: "crochetage",      label: "Crochetage",                  cara: "Ag"  },
  { key: "preparationPoison", label: "Préparation de Poison",     cara: "Int" },
  { key: "lireEcrire",      label: "Lire/Écrire",                 cara: "Int" },
  { key: "navigation",      label: "Navigation",                  cara: "Ag"  },
  { key: "braconnage",      label: "Braconnage",                  cara: "Ag"  },
  { key: "escamotage",      label: "Escamotage",                  cara: "Ag"  },
  { key: "torture",         label: "Torture",                     cara: "Soc" },
  { key: "ventriloquie",    label: "Ventriloquie",                cara: "Soc" }
];

export const BASE_SKILL_LABELS = {
  soinsAnimaux:          'Soins des animaux',
  charisme:              'Charisme',
  commandement:          'Commandement',
  resistancePoison:      'Résistance au Poison',
  deguisement:           'Déguisement',
  conduiteAttelage:      "Conduite d'attelages",
  dissimulation:         'Dissimulation',
  evaluation:            'Évaluation',
  jeu:                   'Jeu',
  commerage:             'Commérage',
  marchandage:           'Marchandage',
  intimidation:          'Intimidation',
  survie:                'Survie',
  perception:            'Perception',
  equitation:            'Équitation',
  canotage:              'Canotage',
  escalade:              'Escalade',
  fouille:               'Fouille',
  deplacementSilencieux: 'Déplacement Silencieux',
  natation:              'Natation',
};

export const BASE_SKILL_CARAC_MAP = {
  soinsAnimaux:          'INT',
  charisme:              'SOC',
  commandement:          'SOC',
  resistancePoison:      'END',
  deguisement:           'SOC',
  conduiteAttelage:      'AGI',
  dissimulation:         'AGI',
  evaluation:            'INT',
  jeu:                   'INT',
  commerage:             'SOC',
  marchandage:           'SOC',
  survie:                'INT',
  perception:            'INT',
  equitation:            'AGI',
  canotage:              'FOR',
  escalade:              'FOR',
  fouille:               'INT',
  deplacementSilencieux: 'AGI',
  natation:              'FOR'
};
