name: Manual Release Warhammer2e

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "Version increment type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION=$(jq -r '.version' system.json)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Calculate new version
        id: bump_version
        run: |
          VERSION=${{ steps.get_version.outputs.current_version }}
          INCREMENT=${{ github.event.inputs.increment }}

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          if [ "$INCREMENT" = "major" ]; then
            MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0
          elif [ "$INCREMENT" = "minor" ]; then
            MINOR=$((MINOR + 1)); PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in system.json
        run: |
          jq ".version = \"${{ steps.bump_version.outputs.new_version }}\"" system.json > tmp.json && mv tmp.json system.json

      - name: Commit updated system.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add system.json
          git commit -m "chore: bump version to ${{ steps.bump_version.outputs.new_version }}"
          git push

      - name: Create ZIP archive
        run: |
          zip -r warhammer2e.zip . -x "*.git*" -x "node_modules/*" -x ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          name: v${{ steps.bump_version.outputs.new_version }}
          files: warhammer2e.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
