name: Build and Release Warhammer2e System

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r warhammer2e.zip . -x "*.git*" -x "node_modules/*" -x ".github/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: warhammer2e.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
